# Generated by Django 4.2 on 2024-10-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'درحال انتظار'), (2, 'تائید شده'), (3, 'رد شده'), (4, 'منقضی شده')], default=1),
        ),
    ]
