# Generated by Django 4.2 on 2024-10-29 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cost_per_one_ton', models.PositiveIntegerField()),
                ('max_cost_per_one_ton', models.PositiveIntegerField()),
                ('min_cost_per_one_km', models.PositiveIntegerField()),
                ('max_cost_per_one_km', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=42, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/transport/car/')),
                ('pelak', models.CharField(max_length=10)),
                ('iran', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/transport/type/')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='TransportReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(blank=True, max_length=42, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=False)),
                ('barnameh', models.CharField(choices=[('ONE_ME', 'one me'), ('UP_TO_YOU', 'up to you')], default='ONE_ME', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_requests', to='transport.location')),
                ('my_transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportreqs', to='transport.transport')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_requests', to='transport.location')),
            ],
            options={
                'verbose_name': 'TransportReq',
                'verbose_name_plural': 'TransportReqs',
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.transporttype'),
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RouteMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('min_duration_hours', models.IntegerField(blank=True, null=True)),
                ('max_duration_hours', models.IntegerField(blank=True, null=True)),
                ('min_cost', models.BigIntegerField(blank=True, null=True)),
                ('max_cost', models.BigIntegerField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='transport.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='transport.location')),
            ],
        ),
    ]
