# Generated by Django 4.2 on 2024-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('weight', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('result', models.BooleanField(choices=[(True, 'OK'), (False, 'NO')], default=True)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
